new

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,78 +1,169 @@
 version: 2.1
+
 orbs:
-  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
-  node: circleci/node@5.0.2
-  eb: circleci/aws-elastic-beanstalk@2.0.1
-  aws-cli: circleci/aws-cli@3.1.1
-  # different jobs are calles later in the workflows sections
+  node: circleci/node@4.1.0
+  aws-cli: circleci/aws-cli@1.3.1
+  eb: circleci/aws-elastic-beanstalk@1.0.0
+  browser-tools: circleci/browser-tools@1.2.3
+
+commands:
+  setup:
+    description: |
+      Install and authenticate with the Elastic Beanstalk CLI. You must have your AWS auth environment variables set for ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_DEFAULT_REGION"].
+    steps:
+      - run:
+          command: |
+            if [[ $EUID == 0 ]]; then export SUDO=""; else # Check if we are root
+              export SUDO="sudo";
+            fi
+            SetupPython() {
+                # setups python3
+                $SUDO apt-get -qq -y install python3-dev
+                SetupPipx
+            }
+            SetupPipx() {
+                if [ "$(which pip | tail -1)" ]; then
+                    echo "pip found"
+                else
+                    echo "pip not found"
+                    $SUDO apt-get update
+                    $SUDO apt-get install -qq -y python3-setuptools
+                    curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | python3
+                fi
+                # install venv with system for pipx
+                # by using pipx we dont have to worry about activating the virtualenv before using eb
+                $SUDO apt-get -qq -y install python3-venv
+                pip install pipx
+            }
+            InstallEBCLI() {
+                if uname -a | grep Darwin > /dev/null 2>&1; then
+                    cd /tmp || { echo "Not able to access /tmp"; return; }
+                    git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
+                    brew install zlib openssl readline
+                    CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib" ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer >/dev/null 2>&1
+                    return $?
+                elif uname -a | grep Linux > /dev/null 2>&1; then
+                    $SUDO apt-get -qq update > /dev/null
+                    # these are the system level deps for the ebcli
+                    $SUDO apt-get -qq -y install build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
+                    if [ "$(which python3 | tail -1)" ]; then
+                        echo "Python3 env found"
+                        SetupPipx
+                    else
+                        echo "Python3 env not found, setting up python with apt"
+                        SetupPython
+                    fi
+                fi
+                    pipx install awsebcli
+                    echo "Complete"
+            }
+            CheckAWSEnvVars() {
+                ERRMSGTEXT="has not been set. This environment variable is required for authentication."
+                if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+                    echo "AWS_ACCESS_KEY_ID $ERRMSGTEXT"
+                    exit 1
+                fi
+                if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+                    echo "AWS_SECRET_ACCESS_KEY $ERRMSGTEXT"
+                    exit 1
+                fi
+                if [ -z "$AWS_DEFAULT_REGION" ]; then
+                    echo "AWS_DEFAULT_REGION $ERRMSGTEXT"
+                    exit 1
+                fi
+            }
+            # Will not run if sourced for bats.
+            # View src/tests for more information.
+            TEST_ENV="bats-core"
+            if [ "${0#*$TEST_ENV}" == "$0" ]; then
+                CheckAWSEnvVars
+                InstallEBCLI
+            fi
+          name: Setting Up Elastic Beanstalk CLI
+
 jobs:
   build:
     docker:
-      # the base image can run most needed actions with orbs
-      - image: "cimg/node:14.15"
-    steps:
-      # install node and checkout code
-      - node/install:
-          node-version: '14.15'         
-      - checkout
-      # Use root level package.json to install dependencies in the frontend app
-      - run:
-          name: Install Front-End Dependencies
-          command: |
-            echo "NODE --version" 
-            echo $(node --version)
-            echo "NPM --version" 
-            echo $(npm --version)
-            npm run frontend:install
-      # TODO: Install dependencies in the the backend API          
-      - run:
-          name: Install API Dependencies
-          command: |
-           echo "TODO: Install dependencies in the the backend API  "
-      # TODO: Lint the frontend
-      - run:
-          name: Front-End Lint
-          command: |
-            echo "TODO: Lint the frontend"
-      # TODO: Build the frontend app
-      - run:
-          name: Front-End Build
-          command: |
-            echo "TODO: Build the frontend app"
-      # TODO: Build the backend API      
-      - run:
-          name: API Build
-          command: |
-            echo "TODO: Build the backend API"
-  # deploy step will run only after manual approval
-  deploy:
-    docker:
       - image: "cimg/base:stable"
-      # more setup needed for aws, node, elastic beanstalk
     steps:
-      - node/install:
-          node-version: '14.15' 
-      - eb/setup
-      - aws-cli/setup
       - checkout
+      - node/install
+      - aws-cli/setup
+      - eb/setup
+      - browser-tools/install-browser-tools
       - run:
-          name: Deploy App
-          # TODO: Install, build, deploy in both apps
+          name: Install Frontend
           command: |
-            echo "# TODO: Install, build, deploy in both apps"
-            
+            npm run install:frontend
+      - run:
+          name: Install Backend
+          command: |
+            npm run install:backend
+      - run:
+          name: Build Frontend
+          command: |
+            npm run build:frontend
+      - run:
+          name: Test Frontend
+          command: |
+            npm run test:frontend
+      - run:
+          name: Build Backend
+          command: |
+            npm run build:backend
+      - run:
+          name: Deployment
+          command: |
+            npm run deploy:frontend
+  deploy:
+    description: |
+      Deploy an update to an existing AWS Elastic Beanstalk environment.
+    docker:
+      - image: <<parameters.image>>
+    parameters:
+      app-dir:
+        default: ./udagram-api
+        description: Path to the directory containing your application source code. My default, the current directory will be used.
+        type: string
+      application-name:
+        default: "udacity"
+        description: The name of the application (used during `eb init`).
+        type: string
+      description:
+        default: ""
+        description: The description for the application version, enclosed in double quotation marks.
+        type: string
+      environment-name:
+        default: "Udacity-env"
+        description: The name of the existing environment (created with `eb create`) to update.
+        type: string
+      image:
+        default: cimg/base:stable
+        description: Enter a custom docker image for this job. By default CircleCI's optimized `cimg/base` image will be used.
+        type: string
+      label:
+        default: ""
+        description: Specify a label to use for the version that the EB CLI creates. If the label has already been used, the EB CLI redeploys the previous version with that label.
+        type: string
+      platform-version:
+        default: node.js
+        description: The platform version to use. You can specify a platform, a platform and version, a platform branch, a solution stack name, or a solution stack ARN. Use 'eb platform list' to get a list of available configurations.
+        type: string
+    steps:
+      - checkout
+      - setup
+      - run:
+          command: |
+             eb deploy Udacity-env
+          name: EB Deploy
+          working_directory: <<parameters.app-dir>>
+
+
+
 workflows:
-  udagram:
+  workflow:
     jobs:
       - build
-      - hold:
-          filters:
-            branches:
-              only:
-                - master
-          type: approval
-          requires:
-            - build
       - deploy:
           requires:
-            - hold
+            - build
